import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "第4课：部署上线，变成一个链接｜Vibe Coding教程",
  description: "跟着狗蛋把本地 AI 工具部署上线，安全配置环境变量，完成作品说明、简历句和第一条真实反馈。",
};

const launchChecks = ["本机能完整跑通：能填、能生成、能看到结果。", "有加载、失败提示和重试按钮。", "至少用 3 条真实样本测试过。", "API Key 没有写进网页或仓库。", "工具名称清楚，别人一看就知道用途。"];
const onlineChecks = ["用手机打开并完整使用一遍，排版没有乱。", "让另一个人用他的设备打开，确认不是只有自己能访问。", "故意不填或乱填，确认不会白屏。", "检查项目和网页源代码，搜索不到任何 sk- 密钥。"];
const portfolioFields = ["工具叫什么", "它解决什么问题", "我怎么发现这个问题", "我做了什么", "我怎么验证它有用", "这个工具不解决什么"];

export default function VibeCodingLessonFourPage() {
  const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
  const courseHref = `${basePath}/vibe-coding/#phase-one-map`;
  return (
    <main className="vibe-lesson-page vibe-lesson4-page">
      <header className="vibe-lesson-header"><a href={courseHref} className="vibe-lesson-brand"><span><Image alt="狗蛋" height={52} src={`${basePath}/mascot/goudan-agent.png`} unoptimized width={52} /></span><div><strong>Vibe Coding教程</strong><small>第一期 · 第 4 课</small></div></a><nav aria-label="课程关卡">{Array.from({ length: 7 }, (_, i) => <a href={`#stage-${i + 1}`} key={i}><b>{i + 1}</b><span>{["检查", "部署", "钥匙", "测试", "作品", "简历", "反馈"][i]}</span></a>)}</nav><a className="vibe-lesson-exit" href={courseHref}>退出课程 ↗</a></header>
      <div className="vibe-lesson-shell">
        <section className="vibe-lesson-hero vibe-lesson4-hero"><div className="vibe-lesson-hero-copy"><span>第 4 课 · 部署上线</span><h1>把它变成一个链接。<br />一个能写进简历的<em>真链接</em>。</h1><p>第三课的工具只能在你电脑上运行。今天，狗蛋陪你把它放到互联网上，让朋友、用户和 HR 点一下就能真正使用。</p><div><b>约 3 小时</b><b>使用 Vercel</b><b>带走作品说明</b></div><a href="#stage-1">准备发射 <strong>↓</strong></a></div><figure><div className="vibe-lesson4-launch"><Image alt="狗蛋准备把项目发射上线" height={1254} src={`${basePath}/mascot/goudan-agent.png`} unoptimized width={1254} /><span>LOCALHOST</span><i>🚀</i><strong>YOUR-APP.VERCEL.APP</strong></div><figcaption><b>狗蛋：</b><code>localhost</code> 发给朋友打不开，公开链接才算作品。</figcaption></figure></section>
        <aside className="vibe-lesson4-definition"><b>什么叫部署？</b><p>把只存在于你电脑里的项目放到互联网平台，让任何人通过链接访问。</p><span>本机项目 → 云端平台 → 公开链接</span></aside>

        <section className="vibe-lesson-stage" id="stage-1"><div className="vibe-lesson-stage-no"><span>STEP</span><b>1</b></div><div className="vibe-lesson-stage-body"><header><span>准备 · 约 25 分钟</span><h2>✅ 上线前检查清单</h2><p>上线之前先确认工具已经准备好。勾不上的项目，回第三课补完再继续。</p></header><div className="vibe-lesson-checklist">{launchChecks.map((item, i) => <label key={item}><input type="checkbox" /><span><b>{i + 1}</b><strong>{item}</strong><small>上线前解决，比上线后救火轻松得多。</small></span></label>)}</div><a className="vibe-lesson-next" href="#stage-2">准备好了，去上线 <span>→</span></a></div></section>

        <section className="vibe-lesson-stage" id="stage-2"><div className="vibe-lesson-stage-no"><span>STEP</span><b>2</b></div><div className="vibe-lesson-stage-body"><header><span>发布 · 约 35 分钟</span><h2>☁️ 部署到 Vercel</h2><p>Vercel 能托管网页和后台代码，也能把密钥安全放在访客看不到的地方。</p></header><ol className="vibe-lesson-steps"><li><b>1</b><span>打开 <code>vercel.com</code>，用 GitHub 或邮箱注册。</span></li><li><b>2</b><span>告诉 AI 编程工具：“请帮我把这个项目部署到 Vercel，我是新手，请一步步告诉我。”</span></li><li><b>3</b><span>按提示导入项目并部署，等待平台生成 <code>项目名.vercel.app</code>。</span></li></ol><form className="vibe-phase2-form"><label><b>贴上你的线上链接</b><input placeholder="https://your-project.vercel.app" type="url" /></label></form><aside className="vibe-lesson-warning"><b>先别急着庆祝</b><p>第一次部署后 AI 可能还不能调用，因为线上环境还没有密钥。下一步会把钥匙放进正确的“保险柜”。</p></aside><a className="vibe-lesson-next" href="#stage-3">配置线上钥匙 <span>→</span></a></div></section>

        <section className="vibe-lesson-stage" id="stage-3"><div className="vibe-lesson-stage-no"><span>STEP</span><b>3</b></div><div className="vibe-lesson-stage-body"><header><span>安全 · 约 30 分钟</span><h2>🔐 给线上工具配置钥匙</h2><p>Vercel 的 Environment Variables 就是线上保险柜：服务器可以读取，网页访客看不到。</p></header><div className="vibe-lesson4-vault"><span>网页和仓库</span><b>禁止出现 API Key</b><i>→</i><span>Environment Variables</span><b>安全保存密钥</b></div><ol className="vibe-lesson-steps"><li><b>1</b><span>询问 AI 编程工具：“这个项目的环境变量叫什么？”</span></li><li><b>2</b><span>进入 Vercel 项目的 <code>Settings → Environment Variables</code>。</span></li><li><b>3</b><span>填写变量名称（如 <code>OPENAI_API_KEY</code>）和密钥内容并保存。</span></li><li><b>4</b><span>重新部署，再打开公开链接测试一次。</span></li></ol><aside className="vibe-lesson-memory"><b>🎯 安全规则 · 1 / 3</b><strong>密钥只去两个地方。</strong><span>本机 .env · 平台环境变量；不进网页、不进群聊、不进截图</span></aside><a className="vibe-lesson-next" href="#stage-4">线上完整测试 <span>→</span></a></div></section>

        <section className="vibe-lesson-stage" id="stage-4"><div className="vibe-lesson-stage-no"><span>STEP</span><b>4</b></div><div className="vibe-lesson-stage-body"><header><span>验收 · 约 25 分钟</span><h2>📱 线上测一遍</h2><p>“我电脑能跑”和“别人也能用”是两回事。换设备、换用户、故意输错，才能看到真实状态。</p></header><div className="vibe-lesson-checklist vibe-lesson4-online">{onlineChecks.map((item, i) => <label key={item}><input type="checkbox" /><span><b>{i + 1}</b><strong>{item}</strong><small>完成后再进入作品包装。</small></span></label>)}</div><aside className="vibe-lesson3-key"><span>SAFE</span><b>搜索 sk-</b><i>项目文件与网页源代码都应为 0 个结果</i></aside><a className="vibe-lesson-next" href="#stage-5">开始写作品说明 <span>→</span></a></div></section>

        <section className="vibe-lesson-stage" id="stage-5"><div className="vibe-lesson-stage-no"><span>STEP</span><b>5</b></div><div className="vibe-lesson-stage-body"><header><span>表达 · 约 30 分钟</span><h2>📄 写一页作品说明</h2><p>链接只能展示工具，作品说明才能让别人看见你如何找到问题、如何验证，以及你做过哪些判断。</p></header><form className="vibe-lesson4-portfolio">{portfolioFields.map((field, i) => <label key={field}><span>0{i + 1}</span><b>{field}</b><textarea rows={3} placeholder={i === 5 ? "诚实写清边界，这一条最显专业" : "用具体事实、原话或数字回答"} /></label>)}</form><div className="vibe-lesson4-preview"><span>PROJECT STORY</span>{portfolioFields.map(field => <div key={field}><b>{field}</b><p>把你的答案整理到这里……</p></div>)}</div><a className="vibe-lesson-next" href="#stage-6">压缩成简历一句话 <span>→</span></a></div></section>

        <section className="vibe-lesson-stage" id="stage-6"><div className="vibe-lesson-stage-no"><span>STEP</span><b>6</b></div><div className="vibe-lesson-stage-body"><header><span>打磨 · 约 20 分钟</span><h2>✍️ 写好简历上的一句话</h2><p>别写“熟练使用 AI”。写清场景、访谈、测试和链接，让事实替你说话。</p></header><form className="vibe-lesson4-resume"><label><b>应用场景</b><input placeholder="校园食堂选择" /></label><label><b>访谈人数</b><input placeholder="5" /></label><label><b>测试样本数</b><input placeholder="5" /></label></form><blockquote className="vibe-lesson4-resume-line">独立调研、开发并上线一个面向「具体场景」的 AI 小工具；通过 N 次用户访谈发现真实问题，用 N 条真实样本测试并迭代，现已部署上线。</blockquote><div className="vibe-prompt-compare"><article><span>❌ 空话</span><p>熟练使用 AI 工具，具备创新能力。</p></article><article><span>✅ 事实</span><p>有真实用户、有测试、有公开链接。</p></article></div><a className="vibe-lesson-next" href="#stage-7">收集第一条反馈 <span>→</span></a></div></section>

        <section className="vibe-lesson-stage" id="stage-7"><div className="vibe-lesson-stage-no"><span>STEP</span><b>7</b></div><div className="vibe-lesson-stage-body"><header><span>交付 · 约 20 分钟</span><h2>💬 收集第一个真实反馈</h2><p>把链接发给两个人，看着他们使用。不要问“好不好”，记录他们卡在哪里、第一句话说了什么。</p></header><form className="vibe-phase2-form"><label><b>他们使用时说的原话</b><textarea placeholder="尤其记录吐槽、误解和停顿" rows={5} /></label><label><b>根据反馈，下一步只改一个点</b><textarea placeholder="写最重要、最值得先改的那一处" rows={4} /></label></form><aside className="vibe-lesson-memory"><b>🎯 安全规则 · 3 / 3</b><strong>上线不是结束，而是第一次真正开始。</strong><span>观察真人 · 记录原话 · 只改最重要的一点</span></aside><a className="vibe-lesson-next" href="#lesson4-complete">完成第四课 <span>→</span></a></div></section>

        <section className="vibe-lesson4-complete" id="lesson4-complete"><div className="vibe-lesson4-trophy"><Image alt="狗蛋庆祝四节课全部完成" height={1254} src={`${basePath}/mascot/goudan-agent.png`} unoptimized width={1254} /><span>🏆</span></div><div><span>🎉 四节课全部完成</span><h2>你做到了。</h2><p>从完全不会编程，到找到真实问题、做出 AI 工具、部署上线并收到真实反馈——这整套过程，才是“会 Vibe Coding”。</p><div className="vibe-lesson4-achievements"><b>真问题</b><b>能用工具</b><b>公开链接</b><b>真实反馈</b></div><blockquote>没上线的项目还只是练习；上线了、有用户、讲得清楚的，才是你的作品。</blockquote><a href={courseHref}>返回课程地图 →</a></div></section>
      </div><footer className="vibe-lesson-footer"><strong>🐶 Minimum Agent Lab · Vibe Coding教程</strong><span>做出来、上了线、讲得清——这才叫作品。</span></footer>
    </main>
  );
}
